/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import type { ThreeElements } from '@react-three/fiber';
import type { ObjectMap } from '@react-three/fiber';
import type { GLTF } from 'three-stdlib';
import type { SkinnedMesh } from 'three';

interface RafebrukeGLTF extends ObjectMap {
  nodes: Record<string, SkinnedMesh>;
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('./assets/Rafeburke.glb') as GLTF &
    RafebrukeGLTF;
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes.Root} />
      <skinnedMesh
        geometry={nodes.Hair.geometry}
        material={materials['N00_000_Hair_00_HAIR (Instance)']}
        skeleton={nodes.Hair.skeleton}
      />
      <skinnedMesh
        name='Face_(merged)'
        geometry={nodes['Face_(merged)'].geometry}
        material={materials['N00_000_00_FaceMouth_00_FACE (Instance)']}
        skeleton={nodes['Face_(merged)'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_1'
        geometry={nodes['Face_(merged)_1'].geometry}
        material={materials['N00_000_00_EyeIris_00_EYE (Instance)']}
        skeleton={nodes['Face_(merged)_1'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_1'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_1'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_2'
        geometry={nodes['Face_(merged)_2'].geometry}
        material={materials['N00_000_00_EyeHighlight_00_EYE (Instance)']}
        skeleton={nodes['Face_(merged)_2'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_2'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_2'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_3'
        geometry={nodes['Face_(merged)_3'].geometry}
        material={materials['N00_000_00_Face_00_SKIN (Instance)']}
        skeleton={nodes['Face_(merged)_3'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_3'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_3'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_4'
        geometry={nodes['Face_(merged)_4'].geometry}
        material={materials['N00_000_00_EyeWhite_00_EYE (Instance)']}
        skeleton={nodes['Face_(merged)_4'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_4'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_4'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_5'
        geometry={nodes['Face_(merged)_5'].geometry}
        material={materials['N00_000_00_FaceBrow_00_FACE (Instance)']}
        skeleton={nodes['Face_(merged)_5'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_5'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_5'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_6'
        geometry={nodes['Face_(merged)_6'].geometry}
        material={materials['N00_000_00_FaceEyelash_00_FACE (Instance)']}
        skeleton={nodes['Face_(merged)_6'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_6'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_6'].morphTargetInfluences}
      />
      <skinnedMesh
        name='Face_(merged)_7'
        geometry={nodes['Face_(merged)_7'].geometry}
        material={materials['N00_000_00_FaceEyeline_00_FACE (Instance)']}
        skeleton={nodes['Face_(merged)_7'].skeleton}
        morphTargetDictionary={nodes['Face_(merged)_7'].morphTargetDictionary}
        morphTargetInfluences={nodes['Face_(merged)_7'].morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)'].geometry}
        material={materials['N00_000_00_Body_00_SKIN (Instance)']}
        skeleton={nodes['Body_(merged)'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_1'].geometry}
        material={materials['N00_000_00_HairBack_00_HAIR (Instance)']}
        skeleton={nodes['Body_(merged)_1'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_2'].geometry}
        material={materials['N00_007_01_Tops_01_CLOTH_01 (Instance)']}
        skeleton={nodes['Body_(merged)_2'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_3'].geometry}
        material={materials['N00_007_01_Tops_01_CLOTH_02 (Instance)']}
        skeleton={nodes['Body_(merged)_3'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_4'].geometry}
        material={materials['N00_007_01_Tops_01_CLOTH_03 (Instance)']}
        skeleton={nodes['Body_(merged)_4'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_5'].geometry}
        material={materials['N00_001_02_Bottoms_01_CLOTH (Instance)']}
        skeleton={nodes['Body_(merged)_5'].skeleton}
      />
      <skinnedMesh
        geometry={nodes['Body_(merged)_6'].geometry}
        material={materials['N00_008_01_Shoes_01_CLOTH (Instance)']}
        skeleton={nodes['Body_(merged)_6'].skeleton}
      />
    </group>
  );
}

useGLTF.preload('/Rafebruke.glb');
